//! Discovering injection regions in a parse tree and resolving them into
//! cacheable, virtual-document-ready form for the LSP bridge.

use std::ops::Range;

use tree_sitter::{Node, Query, QueryCapture, QueryCursor, QueryMatch, StreamingIterator, Tree};
use ulid::Ulid;
use url::Url;

use super::content::{compute_line_column_offsets, extract_clean_content};
use super::language::extract_injection_language;
use super::offset::{InjectionOffset, effective_offset_for_pattern};
use super::ranges::{
    compute_included_ranges, compute_included_ranges_clipped, has_combined_for_pattern,
    has_include_children_for_pattern,
};
use crate::language::LanguageCoordinator;
use crate::language::node_tracker::NodeTracker;
use crate::language::query_predicates::check_match_predicates;
use crate::text::{ceil_char_boundary, clamped_slice, floor_char_boundary, fnv1a_hash};

/// Iterates over the `@injection.content` captures in a query match.
fn iter_injection_content_captures<'a, 'b>(
    match_: &'b QueryMatch<'_, 'a>,
    query: &'b Query,
) -> impl Iterator<Item = QueryCapture<'a>> + 'b {
    match_.captures.iter().copied().filter(|capture| {
        query
            .capture_names()
            .get(capture.index as usize)
            .is_some_and(|name| *name == "injection.content")
    })
}

/// Checks if a node is within the bounds of another node
fn is_node_within(node: &Node, container: &Node) -> bool {
    node.start_byte() >= container.start_byte() && node.end_byte() <= container.end_byte()
}

/// Represents an injection region found in the document
#[derive(Debug, Clone)]
pub(crate) struct InjectionRegionInfo<'a> {
    /// The injection language (e.g., "lua", "yaml")
    pub language: String,
    /// The content node from the injection query
    pub content_node: Node<'a>,
    /// The pattern index (for offset directive lookups)
    pub pattern_index: usize,
    /// Whether `#set! injection.include-children` is set for this pattern.
    /// When true, the injection parser sees the full content node (including named children).
    /// When false, named children (e.g., `block_continuation`) should be excluded.
    pub include_children: bool,
    /// The `#offset!` directive for this pattern, resolved at collection time
    /// (the query goes out of scope before consumers like
    /// `CacheableInjectionRegion::from_region_info` run). `None` when the
    /// pattern has no directive.
    pub offset: Option<InjectionOffset>,
    /// Whether this pattern's captures form one virtual document.
    pub combined: bool,
}

/// Owned injection region for caching (no lifetime dependency on parse tree)
///
/// Unlike `InjectionRegionInfo<'a>`, this struct owns all its data and can be
/// stored in caches that outlive the parse tree. Created via `from_region_info()`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct CacheableInjectionRegion {
    /// The injection language (e.g., "lua", "yaml")
    pub language: String,
    /// Byte range of the injection content in the source
    pub byte_range: Range<usize>,
    /// Line range (0-indexed, inclusive start, exclusive end)
    pub line_range: Range<u32>,
    /// Column offset of the injection content start within its start line,
    /// stored as UTF-16 code units (matching LSP's position encoding).
    /// Non-zero for inline injections (e.g., code within a markdown paragraph).
    /// Only affects the first line (line 0) of the virtual document during
    /// coordinate translation; subsequent lines start at column 0.
    pub start_column: u32,
    /// Unique identifier for associating with cached tokens.
    /// Generated by NodeTracker as a position-based ULID.
    pub region_id: String,
    /// Hash of the injection content for cache invalidation.
    /// Used to detect when cached semantic tokens should be invalidated:
    /// if content_hash changes (or language changes), the cached tokens are stale.
    pub content_hash: u64,
}

/// Compute the (row, UTF-16 column) of `byte_pos`, using a nearby byte with a
/// known row as an anchor: the row counts newlines only in the span between
/// them (offset deltas are typically a few lines, never the whole document).
/// The column additionally scans back from `byte_pos` to its line start —
/// bounded by the current line's length, or by `byte_pos` itself in a
/// document without newlines.
fn position_of_byte(
    text: &str,
    byte_pos: usize,
    anchor_byte: usize,
    anchor_row: usize,
) -> (u32, u32) {
    // Snap both offsets to in-bounds char boundaries: on a stale tree they can
    // be out of range or mid-codepoint, which would panic the slices below.
    let byte_pos = floor_char_boundary(text, byte_pos);
    let anchor_byte = floor_char_boundary(text, anchor_byte);
    let (lo, hi) = (byte_pos.min(anchor_byte), byte_pos.max(anchor_byte));
    let newlines = text[lo..hi].bytes().filter(|&b| b == b'\n').count();
    let row = if byte_pos >= anchor_byte {
        anchor_row + newlines
    } else {
        // Defensive: a stale tree whose row metadata disagrees with `text`
        // must not panic the server on underflow.
        anchor_row.saturating_sub(newlines)
    };
    let line_start = text[..byte_pos].rfind('\n').map(|i| i + 1).unwrap_or(0);
    let column = text[line_start..byte_pos].encode_utf16().count() as u32;
    (row as u32, column)
}

/// Compute clean virtual content and per-line column offsets for an injection region.
///
/// This combines `compute_included_ranges`, `extract_clean_content`, and
/// `compute_line_column_offsets` into a single call, avoiding duplication
/// across resolve methods.
fn extract_virtual_content_and_offsets(
    region: &InjectionRegionInfo,
    cacheable: &CacheableInjectionRegion,
    text: &str,
) -> (String, Vec<u32>) {
    // Child-exclusion gaps restricted to the effective window (#186):
    // cacheable.byte_range already reflects any #offset! directive (applied
    // and char-boundary-aligned by from_region_info), so gaps are clipped to
    // it and relativized to its start. Without an offset the window equals
    // the content node span, so the node-anchored variant gives the same
    // result while reusing tree-sitter's cached node Points (no text scan).
    let included_ranges = if region.offset.is_some() {
        compute_included_ranges_clipped(
            &region.content_node,
            region.include_children,
            text,
            cacheable.byte_range.clone(),
        )
    } else {
        compute_included_ranges(&region.content_node, region.include_children)
    };
    let virtual_content = extract_clean_content(
        text,
        cacheable.byte_range.clone(),
        included_ranges.as_deref(),
    );
    let line_column_offsets = compute_line_column_offsets(
        text,
        cacheable.byte_range.clone(),
        cacheable.start_column,
        included_ranges.as_deref(),
    );
    (virtual_content, line_column_offsets)
}

impl CacheableInjectionRegion {
    /// Create from an InjectionRegionInfo, extracting position data from the node.
    ///
    /// # Panics (debug builds)
    /// Panics if the content node is zero-width (`start_byte >= end_byte`).
    /// Callers must filter zero-width nodes upstream (see `collect_all_injections`).
    pub(crate) fn from_region_info(
        info: &InjectionRegionInfo<'_>,
        region_id: &str,
        text: &str,
    ) -> Self {
        let node = &info.content_node;
        debug_assert!(
            node.start_byte() < node.end_byte(),
            "from_region_info called with zero-width node at byte {}",
            node.start_byte(),
        );

        // #offset! narrows the raw node span to the effective content range
        // (e.g. trimming `---` frontmatter delimiters). The bridge consumes
        // byte_range / line_range / start_column for virtual-document content
        // extraction and coordinate translation, so all of them must reflect
        // the effective range, mirroring the semantic path (#183).
        let (start_byte, end_byte) = match info.offset {
            Some(offset) => {
                use crate::analysis::offset_calculator::{ByteRange, calculate_effective_range};
                // calculate_effective_range clamps, snaps inward to char
                // boundaries, and normalizes start <= end, so slicing below
                // cannot panic.
                let effective = calculate_effective_range(
                    text,
                    ByteRange::new(node.start_byte(), node.end_byte()),
                    offset,
                );
                (effective.start, effective.end)
            }
            None => (node.start_byte(), node.end_byte()),
        };

        // Snap the range to valid in-bounds char boundaries (ceil start / floor
        // end) so the `byte_range` stored below is always safe to slice — a stale
        // node can't leave an out-of-bounds range for downstream consumers, and
        // the direct `content` slice here can't panic. Valid ranges are
        // unchanged; a stale node also stops matching `node.start_byte()` below,
        // routing through the safe `position_of_byte` path.
        let start_byte = ceil_char_boundary(text, start_byte);
        let end_byte = floor_char_boundary(text, end_byte).max(start_byte);
        let content = &text[start_byte..end_byte];

        // Convert tree-sitter byte column to UTF-16 code units for LSP compatibility.
        // Tree-sitter reports columns as byte offsets, but LSP positions use UTF-16.
        // For ASCII they're identical, but non-ASCII prefixes (CJK, emoji) differ.
        // tree-sitter's `column` is a byte offset from the line start, so
        // `start_byte() - column` correctly recovers the line-start byte even
        // when the line contains multi-byte UTF-8 characters before the node.
        let (start_line, start_column) = if start_byte == node.start_byte() {
            let byte_column = node.start_position().column;
            let line_start_byte = node.start_byte().saturating_sub(byte_column);
            let line_prefix = clamped_slice(text, line_start_byte..node.start_byte());
            (
                node.start_position().row as u32,
                line_prefix.encode_utf16().count() as u32,
            )
        } else {
            position_of_byte(
                text,
                start_byte,
                node.start_byte(),
                node.start_position().row,
            )
        };

        // end_position() points past the last byte. When that position is mid-line
        // (column > 0), the node still occupies that row → exclusive end is row + 1.
        // When column == 0 (node ended with newline), the row is already one past
        // the last occupied line — use it directly.
        let end_line = if end_byte == node.end_byte() {
            let end_pos = node.end_position();
            if end_pos.column > 0 {
                end_pos.row as u32 + 1
            } else {
                end_pos.row as u32
            }
        } else {
            let (end_row, end_column) =
                position_of_byte(text, end_byte, node.end_byte(), node.end_position().row);
            if end_column > 0 { end_row + 1 } else { end_row }
        };

        Self {
            language: info.language.clone(),
            byte_range: start_byte..end_byte,
            line_range: start_line..end_line,
            start_column,
            region_id: region_id.to_string(),
            content_hash: Self::hash_content(content),
        }
    }

    /// Compute a simple hash of content bytes for stable matching.
    fn hash_content(content: &str) -> u64 {
        fnv1a_hash(content)
    }
}

/// Collects all injection regions in the document.
///
/// Unlike `detect_injection` (which requires a specific node), this finds ALL
/// injection regions in the whole document — used by semantic tokens to highlight
/// every injected region. `None` when there is no query.
pub(crate) fn collect_all_injections<'a>(
    root: &Node<'a>,
    text: &str,
    injection_query: Option<&Query>,
) -> Option<Vec<InjectionRegionInfo<'a>>> {
    let query = injection_query?;

    let mut cursor = QueryCursor::new();
    let mut matches = cursor.matches(query, *root, text.as_bytes());

    // Deduplicate repeated matches of the same language layer while preserving
    // distinct languages assigned to the same content range (#598).
    let mut injections_map = std::collections::HashMap::new();

    while let Some(match_) = matches.next() {
        if !check_match_predicates(query, match_, text) {
            continue;
        }
        for capture in iter_injection_content_captures(match_, query) {
            if capture.node.start_byte() >= capture.node.end_byte() {
                continue;
            }
            if let Some(language) = extract_injection_language(query, match_, text) {
                let key = (
                    capture.node.start_byte(),
                    capture.node.end_byte(),
                    language.clone(),
                );
                // `or_insert_with` so the per-pattern predicate scans
                // (`has_include_children_for_pattern` / `effective_offset_for_pattern`)
                // are skipped when this content-node range was already inserted by
                // an earlier matching pattern for the same language. Same
                // resulting language layers, fewer scans.
                injections_map.entry(key).or_insert_with(|| {
                    let offset = effective_offset_for_pattern(query, match_.pattern_index);
                    InjectionRegionInfo {
                        language,
                        content_node: capture.node,
                        pattern_index: match_.pattern_index,
                        include_children: has_include_children_for_pattern(
                            query,
                            match_.pattern_index,
                        ),
                        // Match the semantic path: effective offsets and
                        // multi-region grouping do not compose safely.
                        combined: has_combined_for_pattern(query, match_.pattern_index)
                            && offset.is_none(),
                        offset,
                    }
                });
            }
        }
    }

    // Sort by start_byte (primary) and end_byte (secondary) to ensure deterministic ordering
    let mut injections: Vec<_> = injections_map.into_values().collect();
    injections.sort_by(|a, b| {
        (
            a.content_node.start_byte(),
            a.content_node.end_byte(),
            a.pattern_index,
            a.language.as_str(),
        )
            .cmp(&(
                b.content_node.start_byte(),
                b.content_node.end_byte(),
                b.pattern_index,
                b.language.as_str(),
            ))
    });
    Some(injections)
}

/// Detects injection and returns both the language and the content node
/// Also returns the pattern index of the innermost injection for offset lookups
pub(crate) fn detect_injection<'a>(
    node: &Node<'a>,
    root: &Node<'a>,
    text: &str,
    injection_query: Option<&Query>,
    base_language: &str,
) -> Option<(Vec<String>, Node<'a>, usize)> {
    let injections = collect_injection_regions(node, root, text, injection_query)?;

    if injections.is_empty() {
        return None;
    }

    // Sort injections by their range (outer to inner)
    let mut sorted_injections = injections;
    sorted_injections.sort_by(|a, b| {
        // Sort by start byte (ascending), then by end byte (descending)
        // This ensures outer injections come before inner ones. Same-range
        // alternate-language layers tie-break by (pattern_index, language) —
        // the discovery sorts' exact order — so the hierarchy and the
        // innermost pick stay deterministic regardless of input order.
        a.start_byte
            .cmp(&b.start_byte)
            .then(b.end_byte.cmp(&a.end_byte))
            .then(a.pattern_index.cmp(&b.pattern_index))
            .then(a.language.as_str().cmp(b.language.as_str()))
    });

    // Build the language hierarchy from outermost to innermost
    let mut hierarchy = vec![base_language.to_string()];
    for region in &sorted_injections {
        hierarchy.push(region.language.clone());
    }

    // Return the innermost content node and its pattern index
    let innermost = sorted_injections.last()?;

    Some((hierarchy, innermost.content_node, innermost.pattern_index))
}

/// Represents an injection region with its metadata (unresolved intermediate data).
struct RawInjectionRegion<'a> {
    start_byte: usize,
    end_byte: usize,
    language: String,
    content_node: Node<'a>,
    pattern_index: usize,
}

/// Collects all injection regions that contain the given node
/// Returns a list of `RawInjectionRegion` values for each injection containing the node.
fn collect_injection_regions<'a>(
    node: &Node<'a>,
    root: &Node<'a>,
    text: &str,
    injection_query: Option<&Query>,
) -> Option<Vec<RawInjectionRegion<'a>>> {
    let query = injection_query?;

    // Run the query on the entire tree
    let mut cursor = QueryCursor::new();
    let mut matches = cursor.matches(query, *root, text.as_bytes());

    // Collect all injection regions that contain our node
    // Deduplicate by node range and language so alternate language layers on
    // the same node remain discoverable.
    let mut injections_map = std::collections::HashMap::new();

    while let Some(match_) = matches.next() {
        if let Some((content_node, language, pattern_index)) =
            extract_content_and_language(node, match_, query, text)
        {
            let key = (
                content_node.start_byte(),
                content_node.end_byte(),
                language.clone(),
            );

            // Keep the first match for each range/language pair; distinct
            // languages on the same range remain separate layers.
            injections_map.entry(key).or_insert(RawInjectionRegion {
                start_byte: content_node.start_byte(),
                end_byte: content_node.end_byte(),
                language,
                content_node,
                pattern_index,
            });
        }
    }

    let mut injections: Vec<_> = injections_map.into_values().collect();
    injections.sort_by(|a, b| {
        (
            a.start_byte,
            std::cmp::Reverse(a.end_byte),
            a.pattern_index,
            a.language.as_str(),
        )
            .cmp(&(
                b.start_byte,
                std::cmp::Reverse(b.end_byte),
                b.pattern_index,
                b.language.as_str(),
            ))
    });

    Some(injections)
}

/// Extracts the injection content node and language if the given node is within it
/// Also returns the pattern index for offset lookups
fn extract_content_and_language<'a>(
    node: &Node<'a>,
    match_: &QueryMatch<'_, 'a>,
    query: &Query,
    text: &str,
) -> Option<(Node<'a>, String, usize)> {
    for capture in iter_injection_content_captures(match_, query) {
        let content_node = capture.node;

        // Check if our node is within this injection region
        if is_node_within(node, &content_node) {
            if !check_match_predicates(query, match_, text) {
                return None;
            }
            // Extract the injection language
            if let Some(language) = extract_injection_language(query, match_, text) {
                return Some((content_node, language, match_.pattern_index));
            }
        }
    }

    None
}

/// Find the injection region containing the given byte offset.
///
/// Regions are sorted by query pattern index, so same-range alternate
/// languages use explicit query-order priority for single-result bridge APIs.
/// Whole-document and hierarchy discovery still retain every language layer.
///
/// Returns `(index, region)` for use with `calculate_region_id`, or `None` when the
/// position is not within any injection region.
fn find_injection_at_position<'a>(
    injections: &'a [InjectionRegionInfo<'a>],
    byte_offset: usize,
) -> Option<(usize, &'a InjectionRegionInfo<'a>)> {
    injections.iter().enumerate().find(|(_, inj)| {
        let start = inj.content_node.start_byte();
        let end = inj.content_node.end_byte();
        byte_offset >= start && byte_offset < end
    })
}

/// Resolved injection region with all necessary context for LSP bridge requests
#[derive(Clone)]
pub(crate) struct ResolvedInjection {
    /// Cacheable injection region with line range information
    pub region: CacheableInjectionRegion,
    /// Raw language identifier captured or assigned by the injection query.
    pub raw_injection_language: String,
    /// Language of the injection content
    pub injection_language: String,
    /// Extracted virtual document content. Single regions strip excluded
    /// prefixes; combined regions mask excluded host gaps with whitespace.
    pub virtual_content: String,
    /// Per-virtual-line column offsets for coordinate translation.
    /// Each entry is the UTF-16 column offset for that virtual line.
    pub line_column_offsets: Vec<u32>,
    /// Whether `virtual_content` maps to one contiguous host byte range.
    /// `false` for `injection.combined`, whose host-only gaps are masked.
    pub contiguous: bool,
}

/// Central service for resolving injection regions at LSP positions
pub(crate) struct InjectionResolver;

impl InjectionResolver {
    /// Resolve the injection region (if any) covering `byte_offset`. Shared by
    /// LSP handlers (hover, completion, definition, …) at a cursor position.
    ///
    /// Does not hold any Document lock: inputs (`tree`, `text`) must be pre-cloned,
    /// typically via `DocumentSnapshot`.
    #[allow(clippy::too_many_arguments)]
    pub(crate) fn resolve_at_byte_offset(
        coordinator: &LanguageCoordinator,
        tracker: &NodeTracker,
        uri: &Url,
        tree: &Tree,
        text: &str,
        injection_query: &Query,
        byte_offset: usize,
        incarnation: u64,
    ) -> Option<ResolvedInjection> {
        let injections = collect_all_injections(&tree.root_node(), text, Some(injection_query))?;
        let (_region_index, region) = find_injection_at_position(&injections, byte_offset)?;
        if region.combined {
            let group: Vec<_> = injections
                .iter()
                .filter(|candidate| {
                    candidate.combined
                        && candidate.pattern_index == region.pattern_index
                        && candidate.language == region.language
                })
                .collect();
            Self::build_combined_injection(
                coordinator,
                Some((tracker, uri, incarnation)),
                &group,
                None,
                text,
            )
        } else {
            Some(Self::build_resolved_injection(
                coordinator,
                tracker,
                uri,
                region,
                text,
                incarnation,
            ))
        }
    }

    /// Calculate a stable ULID-based region_id for an injection.
    ///
    /// Phase 2 (lazy-node-identity-tracking): keyed on position (start_byte,
    /// end_byte, kind, layer), so the ULID stays constant for the same position
    /// key. Region IDs always use `layer = 0` (see below).
    ///
    /// Minted via the host-layer `get_or_create` (`layer = 0`) **by design**:
    /// `content_node` comes from the host document's injection query, so it is a
    /// host-tree node. The `layer` discriminator (lazy-node-identity-tracking
    /// §"Node Uniqueness Key") only needs to separate host from injected nodes,
    /// and a region's content node is always the host side. If a navigation
    /// `kakehashi/node` call resolves that same host node it dedups to this same
    /// ULID, which is correct.
    pub(crate) fn calculate_region_id(
        tracker: &NodeTracker,
        uri: &Url,
        injection: &InjectionRegionInfo,
        incarnation: u64,
    ) -> Option<Ulid> {
        tracker.get_or_create_for_incarnation(
            uri,
            injection.content_node.start_byte(),
            injection.content_node.end_byte(),
            injection.content_node.kind(),
            incarnation,
        )
    }

    /// Derive a parser-independent canonical injection language for bridge
    /// selection and stable virtual-document identity.
    ///
    /// This derives the stable bridge key from an explicit configured base or
    /// heuristic normalization (for example, `py` to `python`).
    ///
    /// Falls back to the raw identifier when no configured or heuristic
    /// canonical candidate exists; bridge matching then uses that explicit key.
    fn resolve_language(
        coordinator: &LanguageCoordinator,
        raw_identifier: &str,
        content: &str,
    ) -> String {
        coordinator.canonical_injection_language(raw_identifier, content)
    }

    /// Build a [`ResolvedInjection`] from a raw injection region.
    ///
    /// Shared by [`Self::resolve_at_byte_offset`] and [`Self::resolve_all`] to
    /// avoid duplicating the region-id → cacheable-region → virtual-content →
    /// language-resolution pipeline.
    fn build_resolved_injection(
        coordinator: &LanguageCoordinator,
        tracker: &NodeTracker,
        uri: &Url,
        region: &InjectionRegionInfo,
        text: &str,
        incarnation: u64,
    ) -> Option<ResolvedInjection> {
        let region_id = Self::calculate_region_id(tracker, uri, region, incarnation)?;
        let region_id_str = region_id.to_string();
        let cacheable_region =
            CacheableInjectionRegion::from_region_info(region, &region_id_str, text);
        let (virtual_content, line_column_offsets) =
            extract_virtual_content_and_offsets(region, &cacheable_region, text);
        let resolved_language =
            Self::resolve_language(coordinator, &region.language, &virtual_content);
        Some(ResolvedInjection {
            region: cacheable_region,
            raw_injection_language: region.language.clone(),
            injection_language: resolved_language,
            virtual_content,
            line_column_offsets,
            contiguous: true,
        })
    }

    /// Build one bridge virtual document for all captures of an
    /// `injection.combined` pattern. Non-content bytes between captures are
    /// replaced with coordinate-preserving whitespace: the downstream parser
    /// sees one document and retains cross-block context, while every virtual
    /// line/column still maps directly back to the host document.
    fn build_combined_injection(
        coordinator: &LanguageCoordinator,
        identity: Option<(&NodeTracker, &Url, u64)>,
        regions: &[&InjectionRegionInfo<'_>],
        prebuilt: Option<&[&CacheableInjectionRegion]>,
        text: &str,
    ) -> Option<ResolvedInjection> {
        debug_assert!(!regions.is_empty());
        let owned_cacheable;
        let cacheable: Vec<&CacheableInjectionRegion> = match prebuilt {
            Some(cacheable) => cacheable.to_vec(),
            None => {
                let (tracker, uri, incarnation) =
                    identity.expect("non-prebuilt regions require identity");
                owned_cacheable = regions
                    .iter()
                    .map(|region| {
                        let id = Self::calculate_region_id(tracker, uri, region, incarnation)?;
                        Some(CacheableInjectionRegion::from_region_info(
                            region,
                            &id.to_string(),
                            text,
                        ))
                    })
                    .collect::<Option<Vec<_>>>()?;
                owned_cacheable.iter().collect()
            }
        };
        let first = regions[0];
        let first_cacheable = cacheable[0];
        let group_start = first_cacheable.byte_range.start;
        let group_end = cacheable
            .iter()
            .map(|region| region.byte_range.end)
            .max()
            .unwrap_or(group_start);

        let mut included = Vec::new();
        for (region, cacheable) in regions.iter().zip(&cacheable) {
            let ranges = if region.offset.is_some() {
                compute_included_ranges_clipped(
                    &region.content_node,
                    region.include_children,
                    text,
                    cacheable.byte_range.clone(),
                )
            } else {
                compute_included_ranges(&region.content_node, region.include_children)
            };
            match ranges {
                Some(ranges) => included.extend(ranges.into_iter().map(|range| {
                    cacheable.byte_range.start + range.start_byte
                        ..cacheable.byte_range.start + range.end_byte
                })),
                None => included.push(cacheable.byte_range.clone()),
            }
        }
        included.sort_by_key(|range| (range.start, range.end));
        let mut covered_until = group_start;
        let contiguous = included.iter().all(|range| {
            if range.start > covered_until {
                return false;
            }
            covered_until = covered_until.max(range.end);
            true
        }) && covered_until >= group_end;
        let virtual_content = mask_outside_ranges(text, group_start..group_end, &included);

        let mut combined_region = first_cacheable.clone();
        combined_region.byte_range.end = group_end;
        combined_region.line_range.end = cacheable
            .iter()
            .map(|region| region.line_range.end)
            .max()
            .unwrap_or(combined_region.line_range.end);
        combined_region.content_hash = CacheableInjectionRegion::hash_content(&virtual_content);
        let resolved_language =
            Self::resolve_language(coordinator, &first.language, &virtual_content);
        Some(ResolvedInjection {
            region: combined_region,
            raw_injection_language: first.language.clone(),
            injection_language: resolved_language,
            virtual_content,
            line_column_offsets: vec![first_cacheable.start_column],
            contiguous,
        })
    }

    /// Resolve every bridge virtual document in the host (whole-doc operations
    /// like `documentLink` use this rather than a position lookup). Combined
    /// capture groups produce one resolved document. Holds no
    /// Document lock — `tree`/`text` must already be cloned, typically via
    /// `DocumentSnapshot`. Empty vec when nothing matches.
    pub(crate) fn resolve_all(
        coordinator: &LanguageCoordinator,
        tracker: &NodeTracker,
        uri: &Url,
        tree: &Tree,
        text: &str,
        injection_query: &Query,
        incarnation: u64,
    ) -> Vec<ResolvedInjection> {
        let Some(injections) =
            collect_all_injections(&tree.root_node(), text, Some(injection_query))
        else {
            return Vec::new();
        };

        Self::resolve_from_regions(coordinator, tracker, uri, &injections, text, incarnation)
    }

    /// [`resolve_all`](Self::resolve_all) minus the injection-query run, for a
    /// caller that already collected the regions (the populate pass — never
    /// discover twice, parse-snapshot ADR §3).
    pub(crate) fn resolve_from_regions(
        coordinator: &LanguageCoordinator,
        tracker: &NodeTracker,
        uri: &Url,
        regions: &[InjectionRegionInfo<'_>],
        text: &str,
        incarnation: u64,
    ) -> Vec<ResolvedInjection> {
        Self::resolve_grouped(
            coordinator,
            Some((tracker, uri, incarnation)),
            regions,
            None,
            text,
        )
    }

    /// [`resolve_from_regions`](Self::resolve_from_regions) fed with the
    /// `CacheableInjectionRegion`s the caller already built from the SAME
    /// `regions` (populate's path): skips the duplicate per-region id mint
    /// and content hash — populate runs on the pre-publish critical path,
    /// where repeating work the caller just did delays the settle signal.
    /// `regions` and `cacheable` must be index-aligned (both derive from one
    /// `collect_all_injections` pass).
    pub(crate) fn resolve_from_prebuilt(
        coordinator: &LanguageCoordinator,
        regions: &[InjectionRegionInfo<'_>],
        cacheable: &[CacheableInjectionRegion],
        text: &str,
    ) -> Vec<ResolvedInjection> {
        Self::resolve_grouped(coordinator, None, regions, Some(cacheable), text)
    }

    fn resolve_grouped(
        coordinator: &LanguageCoordinator,
        identity: Option<(&NodeTracker, &Url, u64)>,
        regions: &[InjectionRegionInfo<'_>],
        prebuilt: Option<&[CacheableInjectionRegion]>,
        text: &str,
    ) -> Vec<ResolvedInjection> {
        enum Slot {
            Single(usize),
            Combined(Vec<usize>),
        }

        // Partition once in document order. A per-group scan makes dynamic
        // language captures quadratic when nearly every region is its own
        // (language, pattern) group.
        let mut slots = Vec::new();
        let mut combined_slots: std::collections::HashMap<(&str, usize), usize> =
            std::collections::HashMap::new();
        for (index, region) in regions.iter().enumerate() {
            if region.combined {
                let key = (region.language.as_str(), region.pattern_index);
                if let Some(&slot_index) = combined_slots.get(&key) {
                    let Slot::Combined(indices) = &mut slots[slot_index] else {
                        unreachable!("combined slot index must identify a combined slot")
                    };
                    indices.push(index);
                } else {
                    combined_slots.insert(key, slots.len());
                    slots.push(Slot::Combined(vec![index]));
                }
            } else {
                slots.push(Slot::Single(index));
            }
        }

        let mut resolved = Vec::with_capacity(slots.len());
        for slot in slots {
            let index = match slot {
                Slot::Combined(indices) => {
                    let group: Vec<_> = indices.iter().map(|&i| &regions[i]).collect();
                    let prebuilt_group = prebuilt.map(|cacheable| {
                        indices.iter().map(|&i| &cacheable[i]).collect::<Vec<_>>()
                    });
                    if let Some(combined) = Self::build_combined_injection(
                        coordinator,
                        identity,
                        &group,
                        prebuilt_group.as_deref(),
                        text,
                    ) {
                        resolved.push(combined);
                    }
                    continue;
                }
                Slot::Single(index) => index,
            };
            let region = &regions[index];
            if let Some(cacheable) = prebuilt {
                let (virtual_content, line_column_offsets) =
                    extract_virtual_content_and_offsets(region, &cacheable[index], text);
                let resolved_language =
                    Self::resolve_language(coordinator, &region.language, &virtual_content);
                resolved.push(ResolvedInjection {
                    region: cacheable[index].clone(),
                    raw_injection_language: region.language.clone(),
                    injection_language: resolved_language,
                    virtual_content,
                    line_column_offsets,
                    contiguous: true,
                });
            } else {
                let (tracker, uri, incarnation) =
                    identity.expect("non-prebuilt regions require identity");
                if let Some(single) = Self::build_resolved_injection(
                    coordinator,
                    tracker,
                    uri,
                    region,
                    text,
                    incarnation,
                ) {
                    resolved.push(single);
                }
            }
        }
        resolved
    }
}

fn mask_outside_ranges(text: &str, span: Range<usize>, included: &[Range<usize>]) -> String {
    // The output is the span verbatim with excluded bytes turned to spaces
    // (multi-byte chars can shrink it, never grow it) — preallocate the span.
    let mut output = String::with_capacity(span.len());
    let mut cursor = span.start;
    for range in included {
        let start = range.start.clamp(cursor, span.end);
        let end = range.end.clamp(start, span.end);
        push_coordinate_whitespace(&mut output, clamped_slice(text, cursor..start));
        output.push_str(clamped_slice(text, start..end));
        cursor = end;
    }
    push_coordinate_whitespace(&mut output, clamped_slice(text, cursor..span.end));
    output
}

fn push_coordinate_whitespace(output: &mut String, text: &str) {
    for character in text.chars() {
        if matches!(character, '\n' | '\r') {
            output.push(character);
        } else {
            output.extend(std::iter::repeat_n(' ', character.len_utf16()));
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::language::LanguageCoordinator;
    use crate::language::node_tracker::NodeTracker;
    use rstest::rstest;
    use tree_sitter::{Node, Parser, Query, StreamingIterator};
    use url::Url;

    fn create_rust_parser() -> Parser {
        let mut parser = Parser::new();
        parser
            .set_language(&tree_sitter_rust::LANGUAGE.into())
            .expect("load rust grammar");
        parser
    }

    fn parse_rust_code(parser: &mut Parser, code: &str) -> tree_sitter::Tree {
        parser.parse(code, None).expect("parse rust")
    }

    // Helper function to find a node at a specific byte position
    fn find_node_at_byte<'a>(root: &Node<'a>, byte: usize) -> Option<Node<'a>> {
        root.descendant_for_byte_range(byte, byte)
    }

    fn test_uri(name: &str) -> Url {
        Url::parse(&format!("file:///test/{}.rs", name)).unwrap()
    }

    fn test_coordinator() -> LanguageCoordinator {
        LanguageCoordinator::new()
    }

    #[test]
    fn canonicalizes_token_independently_of_parser_availability() {
        let coordinator = LanguageCoordinator::new();

        assert_eq!(
            InjectionResolver::resolve_language(&coordinator, "py", "print('hello')"),
            "python"
        );

        coordinator
            .language_registry_for_parallel()
            .register("py".to_string(), tree_sitter_python::LANGUAGE.into());
        assert_eq!(
            InjectionResolver::resolve_language(&coordinator, "py", "print('hello')"),
            "python"
        );
    }

    #[test]
    fn explicit_token_beats_loaded_first_line_language() {
        let coordinator = LanguageCoordinator::new();
        coordinator
            .language_registry_for_parallel()
            .register("lua".to_string(), tree_sitter_lua::LANGUAGE.into());

        assert_eq!(
            InjectionResolver::resolve_language(
                &coordinator,
                "py",
                "#!/usr/bin/env lua\nprint('hello')",
            ),
            "python"
        );
    }

    #[test]
    fn configured_base_beats_syntect_token_normalization_without_parser() {
        let coordinator = LanguageCoordinator::new();
        coordinator.load_settings(&crate::config::WorkspaceSettings {
            languages: std::collections::HashMap::from([(
                "py".to_string(),
                crate::config::settings::LanguageSettings {
                    base: Some("custom-python".to_string()),
                    ..Default::default()
                },
            )]),
            ..Default::default()
        });

        assert_eq!(
            InjectionResolver::resolve_language(&coordinator, "py", ""),
            "custom-python"
        );
    }

    #[test]
    fn canonicalizes_first_line_without_loaded_parser() {
        let coordinator = LanguageCoordinator::new();

        assert_eq!(
            InjectionResolver::resolve_language(
                &coordinator,
                "unknown",
                "#!/usr/bin/env python\nprint('hello')",
            ),
            "python"
        );
    }

    #[test]
    fn configured_plaintext_base_is_canonical_for_bridge() {
        let coordinator = LanguageCoordinator::new();
        coordinator.load_settings(&crate::config::WorkspaceSettings {
            languages: std::collections::HashMap::from([(
                "plaintext".to_string(),
                crate::config::settings::LanguageSettings {
                    base: Some("python".to_string()),
                    ..Default::default()
                },
            )]),
            ..Default::default()
        });

        assert_eq!(
            InjectionResolver::resolve_language(&coordinator, "plaintext", ""),
            "python"
        );
    }

    #[test]
    fn explicit_plaintext_ignores_first_line_heuristics() {
        let coordinator = LanguageCoordinator::new();

        assert_eq!(
            InjectionResolver::resolve_language(
                &coordinator,
                "plaintext",
                "#!/usr/bin/env python\nprint('hello')",
            ),
            "plaintext"
        );
    }

    /// Helper: parse `text` with tree-sitter Rust, match `string_content` nodes
    /// via injection query, and return the `CacheableInjectionRegion` for the first match.
    fn cacheable_from_first_injection(text: &str) -> CacheableInjectionRegion {
        let mut parser = create_rust_parser();
        let tree = parse_rust_code(&mut parser, text);
        let root = tree.root_node();

        let query_str = r#"
            ((string_literal
              (string_content) @injection.content)
             (#set! injection.language "test"))
        "#;
        let language = tree_sitter_rust::LANGUAGE.into();
        let query = Query::new(&language, query_str).expect("valid query");

        let regions =
            collect_all_injections(&root, text, Some(&query)).expect("should find injections");
        assert!(!regions.is_empty(), "expected at least one injection");

        CacheableInjectionRegion::from_region_info(&regions[0], "test-id", text)
    }

    #[test]
    fn test_detect_nested_injections() {
        use tree_sitter::Parser;

        // Simulate a markdown file with a code block
        let mut parser = Parser::new();
        let language = tree_sitter_rust::LANGUAGE.into();
        parser.set_language(&language).expect("load rust grammar");

        let text = r#"let x = "markdown with ```lua code```";"#;
        let tree = parser.parse(text, None).expect("parse rust");
        let root = tree.root_node();

        // Create a mock injection query that simulates nested injections
        let query_str = r#"
        (string_literal
          (string_content) @injection.content
          (#set! injection.language "markdown"))
        "#;

        let query = Query::new(&language, query_str).expect("valid query");

        // Find a node within the string content
        let node_in_string = find_node_at_byte(&root, 20).expect("node at position");

        // Detect injection with content
        let result = detect_injection(&node_in_string, &root, text, Some(&query), "rust");

        assert!(result.is_some());
        let (hierarchy, _content_node, _pattern_index) = result.unwrap();

        // Should detect rust -> markdown hierarchy
        assert_eq!(hierarchy, vec!["rust", "markdown"]);
    }

    #[test]
    fn test_detect_injection_with_static_language() {
        let mut parser = create_rust_parser();
        let text = r#"fn main() { let re = Regex::new(r"^\d+$").unwrap(); }"#;
        let tree = parse_rust_code(&mut parser, text);
        let root = tree.root_node();

        // Create a query that matches Regex::new with static language
        let query_str = r#"
            (call_expression
              function: (scoped_identifier
                path: (identifier) @_regex
                (#eq? @_regex "Regex")
                name: (identifier) @_new
                (#eq? @_new "new"))
              arguments: (arguments
                (raw_string_literal
                  (string_content) @injection.content))
              (#set! injection.language "regex"))
        "#;

        let language = tree_sitter_rust::LANGUAGE.into();
        let query = Query::new(&language, query_str).expect("valid query");

        // Find a node inside the regex string
        let node = find_node_at_byte(&root, 35); // Position in regex string
        assert!(node.is_some());

        let result = detect_injection(&node.unwrap(), &root, text, Some(&query), "rust");
        assert_eq!(
            result.map(|(h, _, _)| h),
            Some(vec!["rust".to_string(), "regex".to_string()])
        );
    }

    #[test]
    fn test_detect_injection_with_no_injection() {
        let mut parser = create_rust_parser();
        let text = r#"fn main() { println!("hello"); }"#;
        let tree = parse_rust_code(&mut parser, text);
        let root = tree.root_node();

        // Query that won't match
        let query_str = r#"
            (call_expression
              function: (identifier) @_fn
              (#eq? @_fn "nonexistent")
              (arguments) @injection.content
              (#set! injection.language "test"))
        "#;

        let language = tree_sitter_rust::LANGUAGE.into();
        let query = Query::new(&language, query_str).expect("valid query");

        let node = find_node_at_byte(&root, 20); // Position in string
        assert!(node.is_some());

        let result = detect_injection(&node.unwrap(), &root, text, Some(&query), "rust");
        assert_eq!(result.map(|(h, _, _)| h), None);
    }

    #[test]
    fn test_detect_injection_without_query() {
        let mut parser = create_rust_parser();
        let text = r#"fn main() { }"#;
        let tree = parse_rust_code(&mut parser, text);
        let root = tree.root_node();

        let node = root.child(0).unwrap();
        let result = detect_injection(&node, &root, text, None, "rust");
        assert_eq!(result, None);
    }

    #[test]
    fn test_is_node_within() {
        let mut parser = create_rust_parser();
        let text = r#"fn main() { let x = 42; }"#;
        let tree = parse_rust_code(&mut parser, text);
        let root = tree.root_node();

        let outer = root.child(0).unwrap(); // function_item
        let inner = find_node_at_byte(&root, 20).unwrap(); // Some node inside

        assert!(is_node_within(&inner, &outer));
        assert!(!is_node_within(&outer, &inner));
    }

    #[test]
    fn test_recursive_injection_depth_limit() {
        // Test that we can handle multiple levels of injection
        // This is a simple test - real recursive injection happens in refactor.rs

        let mut parser = create_rust_parser();
        let text = r#"fn main() { let x = "nested"; }"#;
        let tree = parse_rust_code(&mut parser, text);
        let root = tree.root_node();

        // Create a query that would inject strings as another language
        let query_str = r#"
        ((string_literal
          (string_content) @injection.content)
         (#set! injection.language "nested_lang"))
        "#;

        let language = tree_sitter_rust::LANGUAGE.into();
        let query = Query::new(&language, query_str).expect("valid query");

        let node = find_node_at_byte(&root, 22).expect("node in string");
        let result = detect_injection(&node, &root, text, Some(&query), "rust");

        assert!(result.is_some());
        let (hierarchy, _, _) = result.unwrap();
        assert_eq!(hierarchy, vec!["rust", "nested_lang"]);

        // The actual deep recursion is tested through integration with refactor.rs
        // where handle_nested_injection recursively processes injections
    }

    #[test]
    fn resolve_all_combines_regions_marked_combined() {
        let mut parser = create_rust_parser();
        let text = r#"fn main() { let open = "<div>"; let close = "</div>"; }"#;
        let tree = parse_rust_code(&mut parser, text);
        let language = tree_sitter_rust::LANGUAGE.into();
        let query = Query::new(
            &language,
            r#"
                ((string_literal
                   (string_content) @injection.content)
                 (#set! injection.language "html")
                 (#set! injection.combined))
            "#,
        )
        .expect("valid query");
        let coordinator = test_coordinator();
        let tracker = NodeTracker::new();
        let uri = test_uri("combined");

        let resolved =
            InjectionResolver::resolve_all(&coordinator, &tracker, &uri, &tree, text, &query);

        assert_eq!(resolved.len(), 1, "combined captures form one document");
        assert!(resolved[0].virtual_content.contains("<div>"));
        assert!(resolved[0].virtual_content.contains("</div>"));
        assert!(!resolved[0].virtual_content.contains("let close"));
        assert!(!resolved[0].contiguous);
    }

    #[test]
    fn single_combined_capture_remains_contiguous() {
        let mut parser = create_rust_parser();
        let text = r#"fn main() { let html = "<div></div>"; }"#;
        let tree = parse_rust_code(&mut parser, text);
        let language = tree_sitter_rust::LANGUAGE.into();
        let query = Query::new(
            &language,
            r#"
                ((string_literal
                   (string_content) @injection.content)
                 (#set! injection.language "html")
                 (#set! injection.combined))
            "#,
        )
        .expect("valid query");

        let resolved = InjectionResolver::resolve_all(
            &test_coordinator(),
            &NodeTracker::new(),
            &test_uri("single_combined"),
            &tree,
            text,
            &query,
        );

        assert_eq!(resolved.len(), 1);
        assert!(resolved[0].contiguous);
        assert_eq!(resolved[0].virtual_content, "<div></div>");
    }

    #[test]
    fn combined_patterns_with_offsets_remain_separate() {
        let mut parser = create_rust_parser();
        let text = r#"fn main() { let a = "abc"; let b = "def"; }"#;
        let tree = parse_rust_code(&mut parser, text);
        let language = tree_sitter_rust::LANGUAGE.into();
        let query = Query::new(
            &language,
            r#"
                ((string_literal
                   (string_content) @injection.content)
                 (#set! injection.language "html")
                 (#set! injection.combined)
                 (#offset! @injection.content 0 1 0 -1))
            "#,
        )
        .expect("valid query");

        let resolved = InjectionResolver::resolve_all(
            &test_coordinator(),
            &NodeTracker::new(),
            &test_uri("combined_offset"),
            &tree,
            text,
            &query,
        );

        assert_eq!(resolved.len(), 2);
        assert_eq!(resolved[0].virtual_content, "b");
        assert_eq!(resolved[1].virtual_content, "e");
        assert!(resolved.iter().all(|region| region.contiguous));
    }

    #[test]
    fn same_range_injections_keep_distinct_languages() {
        let mut parser = create_rust_parser();
        let text = r#"fn main() { /* comment */ }"#;
        let tree = parse_rust_code(&mut parser, text);
        let root = tree.root_node();

        // Create a mock query that would inject the same node twice
        // This simulates what happens with luadoc -> comment
        let query_str = r#"
        ((block_comment) @injection.content
         (#set! injection.language "doc"))

        ((block_comment) @injection.content
         (#set! injection.language "comment"))
        "#;

        let language = tree_sitter_rust::LANGUAGE.into();
        let query = Query::new(&language, query_str).expect("valid query");

        // Find a node inside the comment
        // The injection query matches on block_comment nodes, so we need to be inside one
        let mut cursor = tree_sitter::QueryCursor::new();
        let mut matches = cursor.matches(&query, root, text.as_bytes());

        let mut injection_count = 0;
        while let Some(_match) = matches.next() {
            injection_count += 1;
        }

        // This should find 2 matches (both patterns match the same comment)
        assert_eq!(injection_count, 2, "Expected 2 injection patterns to match");

        // Now test our detection from inside the comment
        let node_in_comment = find_node_at_byte(&root, 14).expect("node in comment");
        let result = detect_injection(&node_in_comment, &root, text, Some(&query), "rust");

        assert!(result.is_some(), "Should find injection");
        let (hierarchy, _, _) = result.unwrap();
        assert_eq!(
            hierarchy,
            vec!["rust", "doc", "comment"],
            "distinct language layers on the same node must survive discovery"
        );
    }

    #[test]
    fn same_range_bridge_resolution_uses_query_pattern_priority() {
        let mut parser = create_rust_parser();
        let text = r#"fn main() { /* comment */ }"#;
        let tree = parse_rust_code(&mut parser, text);
        let language = tree_sitter_rust::LANGUAGE.into();
        let query = Query::new(
            &language,
            r#"
                ((block_comment) @injection.content
                 (#set! injection.language "doc"))
                ((block_comment) @injection.content
                 (#set! injection.language "comment"))
            "#,
        )
        .expect("valid query");

        let all = collect_all_injections(&tree.root_node(), text, Some(&query)).unwrap();
        assert_eq!(
            all.len(),
            2,
            "both same-range languages remain discoverable"
        );
        let resolved = InjectionResolver::resolve_at_byte_offset(
            &test_coordinator(),
            &NodeTracker::new(),
            &test_uri("same_range_priority"),
            &tree,
            text,
            &query,
            15,
        )
        .expect("comment position resolves");

        assert_eq!(resolved.region.language, "doc");
    }

    #[test]
    fn test_cacheable_injection_region_from_region_info() {
        // Create a parser and parse some code to get a real Node
        let mut parser = create_rust_parser();
        let text = r#"fn main() { let s = "hello"; }"#;
        let tree = parse_rust_code(&mut parser, text);
        let root = tree.root_node();

        // Create an injection query that matches the string
        let query_str = r#"
            ((string_literal) @injection.content
              (#set! injection.language "markdown"))
        "#;
        let language = tree_sitter_rust::LANGUAGE.into();
        let query = Query::new(&language, query_str).expect("valid query");

        // Get injection regions
        let regions = collect_all_injections(&root, text, Some(&query));
        let regions = regions.expect("Should find injections");
        assert!(!regions.is_empty(), "Should find at least one injection");

        let region_info = &regions[0];

        // Convert to CacheableInjectionRegion (owned, no lifetime)
        let cacheable =
            CacheableInjectionRegion::from_region_info(region_info, "test-result-id", text);

        // Verify all fields are captured correctly
        assert_eq!(cacheable.language, "markdown");
        assert_eq!(
            cacheable.byte_range.start,
            region_info.content_node.start_byte()
        );
        assert_eq!(
            cacheable.byte_range.end,
            region_info.content_node.end_byte()
        );
        assert_eq!(
            cacheable.line_range.start,
            region_info.content_node.start_position().row as u32
        );
        assert_eq!(
            cacheable.line_range.end,
            region_info.content_node.start_position().row as u32 + 1
        );
        assert_eq!(cacheable.region_id, "test-result-id");
    }

    #[test]
    fn test_from_region_info_applies_column_offset() {
        // #offset! with a column delta (e.g. regex content after a prefix)
        // must shift byte_range and start_column to the effective position,
        // so the bridge extracts the right content and translates coordinates
        // correctly (#183).
        let mut parser = create_rust_parser();
        let text = "// regex content";
        let tree = parse_rust_code(&mut parser, text);
        let root = tree.root_node();

        let query_str = r#"
            ((line_comment) @injection.content
              (#set! injection.language "regex")
              (#offset! @injection.content 0 3 0 0))
        "#;
        let language = tree_sitter_rust::LANGUAGE.into();
        let query = Query::new(&language, query_str).expect("valid query");

        let regions = collect_all_injections(&root, text, Some(&query)).expect("injections");
        assert_eq!(regions.len(), 1);
        let cacheable = CacheableInjectionRegion::from_region_info(&regions[0], "test-id", text);

        assert_eq!(&text[cacheable.byte_range.clone()], "regex content");
        assert_eq!(cacheable.byte_range, 3..text.len());
        assert_eq!(cacheable.start_column, 3);
        assert_eq!(cacheable.line_range, 0..1);
    }

    #[test]
    fn test_from_region_info_applies_row_offset_for_frontmatter() {
        // The vendored markdown query trims `---` frontmatter delimiters via
        // (#offset! @injection.content 1 0 -1 0); the cacheable region must
        // reflect the effective (delimiter-free) range (#183).
        let md_language: tree_sitter::Language = tree_sitter_md::LANGUAGE.into();
        let mut parser = Parser::new();
        parser.set_language(&md_language).expect("set md language");
        let text = "---\ntitle: x\n---\n\n# heading\n";
        let tree = parser.parse(text, None).expect("parse markdown");
        let root = tree.root_node();

        let query_str = r#"
            ((minus_metadata) @injection.content
              (#set! injection.language "yaml")
              (#set! injection.include-children)
              (#offset! @injection.content 1 0 -1 0))
        "#;
        let query = Query::new(&md_language, query_str).expect("valid query");

        let regions = collect_all_injections(&root, text, Some(&query)).expect("injections");
        assert_eq!(regions.len(), 1);
        let cacheable = CacheableInjectionRegion::from_region_info(&regions[0], "test-id", text);

        assert_eq!(&text[cacheable.byte_range.clone()], "title: x\n");
        assert_eq!(cacheable.line_range, 1..2);
        assert_eq!(cacheable.start_column, 0);
    }

    #[test]
    fn test_resolved_injection_virtual_content_honors_offset() {
        // End-to-end through the bridge resolution path: the virtual document
        // sent downstream must contain only the effective (post-offset)
        // content, not the raw node text with delimiters (#183).
        let md_language: tree_sitter::Language = tree_sitter_md::LANGUAGE.into();
        let mut parser = Parser::new();
        parser.set_language(&md_language).expect("set md language");
        let text = "---\ntitle: x\n---\n\n# heading\n";
        let tree = parser.parse(text, None).expect("parse markdown");

        let query_str = r#"
            ((minus_metadata) @injection.content
              (#set! injection.language "yaml")
              (#set! injection.include-children)
              (#offset! @injection.content 1 0 -1 0))
        "#;
        let query = Query::new(&md_language, query_str).expect("valid query");

        let coordinator = test_coordinator();
        let tracker = NodeTracker::new();
        let uri = test_uri("offset_frontmatter");

        let resolved =
            InjectionResolver::resolve_all(&coordinator, &tracker, &uri, &tree, text, &query, 0);
        assert_eq!(resolved.len(), 1);
        assert_eq!(resolved[0].virtual_content, "title: x\n");
        assert_eq!(resolved[0].region.line_range.start, 1);
        assert_eq!(resolved[0].line_column_offsets, vec![0]);
    }

    #[test]
    fn test_resolved_virtual_content_combines_offset_with_child_exclusion() {
        // #186: a query with #offset! but WITHOUT injection.include-children.
        // Blockquote `> ` prefixes (block_continuation children) must still be
        // stripped, restricted to the post-offset window — previously the
        // child-exclusion step was skipped entirely whenever an offset was
        // active, leaking prefixes into the virtual document.
        let md_language: tree_sitter::Language = tree_sitter_md::LANGUAGE.into();
        let mut parser = Parser::new();
        parser.set_language(&md_language).expect("set md language");
        let text = "> ```lua\n> local a = 1\n> local b = 2\n> ```\n";
        let tree = parser.parse(text, None).expect("parse markdown");

        let query_str = r#"
            ((fenced_code_block
               (info_string (language) @injection.language)
               (code_fence_content) @injection.content)
              (#offset! @injection.content 1 0 0 0))
        "#;
        let query = Query::new(&md_language, query_str).expect("valid query");

        let coordinator = test_coordinator();
        let tracker = NodeTracker::new();
        let uri = test_uri("offset_blockquote");

        let resolved =
            InjectionResolver::resolve_all(&coordinator, &tracker, &uri, &tree, text, &query, 0);
        assert_eq!(resolved.len(), 1);
        // The row offset trims the first content line; child exclusion strips
        // the remaining `> ` prefixes.
        assert_eq!(resolved[0].virtual_content, "local b = 2\n");
    }

    #[test]
    fn test_resolve_injection_returns_ulid_format() {
        // Test that resolved injection has region_id in ULID format (26 chars)
        let mut parser = create_rust_parser();
        let text = r#"fn main() { let s = "hello"; }"#;
        let tree = parse_rust_code(&mut parser, text);

        let query_str = r#"
            ((string_literal) @injection.content
              (#set! injection.language "lua"))
        "#;
        let language = tree_sitter_rust::LANGUAGE.into();
        let query = Query::new(&language, query_str).expect("valid query");

        let coordinator = test_coordinator();
        let tracker = NodeTracker::new();
        let uri = test_uri("ulid_format");

        // Resolve injection at byte offset inside the string literal
        let resolved = InjectionResolver::resolve_at_byte_offset(
            &coordinator,
            &tracker,
            &uri,
            &tree,
            text,
            &query,
            22,
            0,
        );
        assert!(resolved.is_some(), "Should resolve injection");
        let region_id = resolved.unwrap().region.region_id;
        assert_eq!(
            region_id.len(),
            26,
            "ULID should be 26 characters, got: {}",
            region_id
        );
    }

    #[test]
    fn test_resolve_injection_multiple_regions_stable_ulids() {
        // Test that multiple injection regions get stable ULIDs for same ordinal
        let mut parser = create_rust_parser();
        let text = r#"fn main() { let a = "hello"; let b = "world"; let c = "test"; }"#;
        let tree = parse_rust_code(&mut parser, text);

        let query_str = r#"
            ((string_literal) @injection.content
              (#set! injection.language "lua"))
        "#;
        let language = tree_sitter_rust::LANGUAGE.into();
        let query = Query::new(&language, query_str).expect("valid query");

        let coordinator = test_coordinator();
        let tracker = NodeTracker::new();
        let uri = test_uri("multiple");

        // Find byte offsets for each string
        let query_all = Query::new(&language, r#"(string_literal) @str"#).expect("valid query");
        let mut cursor = tree_sitter::QueryCursor::new();
        let mut matches_iter = cursor.matches(&query_all, tree.root_node(), text.as_bytes());
        let mut byte_offsets = Vec::new();
        while let Some(m) = matches_iter.next() {
            byte_offsets.push(m.captures[0].node.start_byte() + 1);
        }
        assert_eq!(byte_offsets.len(), 3, "Should find 3 strings");

        // Resolve each injection
        let r1 = InjectionResolver::resolve_at_byte_offset(
            &coordinator,
            &tracker,
            &uri,
            &tree,
            text,
            &query,
            byte_offsets[0],
            0,
        );
        let r2 = InjectionResolver::resolve_at_byte_offset(
            &coordinator,
            &tracker,
            &uri,
            &tree,
            text,
            &query,
            byte_offsets[1],
            0,
        );
        let r3 = InjectionResolver::resolve_at_byte_offset(
            &coordinator,
            &tracker,
            &uri,
            &tree,
            text,
            &query,
            byte_offsets[2],
            0,
        );

        // Each should have different ULIDs (different ordinals)
        let id1 = r1.unwrap().region.region_id;
        let id2 = r2.unwrap().region.region_id;
        let id3 = r3.unwrap().region.region_id;
        assert_ne!(id1, id2, "Different ordinals should have different ULIDs");
        assert_ne!(id2, id3, "Different ordinals should have different ULIDs");
        assert_ne!(id1, id3, "Different ordinals should have different ULIDs");
    }

    #[test]
    fn test_resolve_injection_same_position_returns_consistent_region_id() {
        // Test that resolving the same position returns consistent region_id
        let mut parser = create_rust_parser();
        let text = r#"fn main() { let s = "hello"; }"#;
        let tree = parse_rust_code(&mut parser, text);

        let query_str = r#"
            ((string_literal) @injection.content
              (#set! injection.language "lua"))
        "#;
        let language = tree_sitter_rust::LANGUAGE.into();
        let query = Query::new(&language, query_str).expect("valid query");

        let coordinator = test_coordinator();
        let tracker = NodeTracker::new();
        let uri = test_uri("consistent");

        // Resolve the same position multiple times
        let byte_offset = 22;
        let r1 = InjectionResolver::resolve_at_byte_offset(
            &coordinator,
            &tracker,
            &uri,
            &tree,
            text,
            &query,
            byte_offset,
            0,
        );
        let r2 = InjectionResolver::resolve_at_byte_offset(
            &coordinator,
            &tracker,
            &uri,
            &tree,
            text,
            &query,
            byte_offset,
            0,
        );

        assert_eq!(
            r1.unwrap().region.region_id,
            r2.unwrap().region.region_id,
            "Same position should return same region_id"
        );
    }

    #[test]
    fn test_calculate_region_id_different_positions_different_ulids() {
        // Test that different injection positions produce different ULIDs
        // Phase 2: Uses position-based keys (start_byte, end_byte, kind)
        let mut parser = create_rust_parser();
        let text = r#"fn main() { let a = "lua1"; let b = "python"; let c = "lua2"; }"#;
        let tree = parse_rust_code(&mut parser, text);
        let root = tree.root_node();

        let mut cursor = tree_sitter::QueryCursor::new();
        let query_str = r#"(string_literal) @str"#;
        let language = tree_sitter_rust::LANGUAGE.into();
        let query = Query::new(&language, query_str).expect("valid query");

        let mut matches_iter = cursor.matches(&query, root, text.as_bytes());
        let mut nodes = Vec::new();
        while let Some(m) = matches_iter.next() {
            nodes.push(m.captures[0].node);
        }
        assert_eq!(nodes.len(), 3, "Should find 3 strings");

        // Create injection regions manually: lua, python, lua
        let injections = [
            InjectionRegionInfo {
                language: "lua".to_string(),
                content_node: nodes[0],
                pattern_index: 0,
                include_children: false,
                offset: None,
                combined: false,
            },
            InjectionRegionInfo {
                language: "python".to_string(),
                content_node: nodes[1],
                pattern_index: 0,
                include_children: false,
                offset: None,
                combined: false,
            },
            InjectionRegionInfo {
                language: "lua".to_string(),
                content_node: nodes[2],
                pattern_index: 0,
                include_children: false,
                offset: None,
                combined: false,
            },
        ];

        let tracker = NodeTracker::new();
        let uri = test_uri("mixed");

        // Phase 2: calculate_region_id uses position-based keys (not ordinals)
        // Different positions → different ULIDs regardless of language
        let ulid_0 = InjectionResolver::calculate_region_id(&tracker, &uri, &injections[0], 0)
            .expect("unmanaged test tracker admits the mint");
        let ulid_1 = InjectionResolver::calculate_region_id(&tracker, &uri, &injections[1], 0)
            .expect("unmanaged test tracker admits the mint");
        let ulid_2 = InjectionResolver::calculate_region_id(&tracker, &uri, &injections[2], 0)
            .expect("unmanaged test tracker admits the mint");

        // All different because they have different byte positions
        assert_ne!(
            ulid_0, ulid_1,
            "Different positions should have different ULIDs"
        );
        assert_ne!(
            ulid_1, ulid_2,
            "Different positions should have different ULIDs"
        );
        assert_ne!(
            ulid_0, ulid_2,
            "Different positions should have different ULIDs"
        );

        // Same position returns same ULID (stability)
        let ulid_0_again =
            InjectionResolver::calculate_region_id(&tracker, &uri, &injections[0], 0)
                .expect("same-lifetime remint is admitted");
        assert_eq!(
            ulid_0, ulid_0_again,
            "Same position key should return same ULID"
        );
    }

    #[test]
    fn test_find_injection_at_position_returns_correct_region_and_index() {
        // Test that find_injection_at_position returns the correct region and its index
        // for use with calculate_region_id

        let mut parser = create_rust_parser();
        let text = r#"fn main() { let a = "lua1"; let b = "py"; let c = "lua2"; }"#;
        let tree = parse_rust_code(&mut parser, text);
        let root = tree.root_node();

        // Find all string_literal nodes
        let mut cursor = tree_sitter::QueryCursor::new();
        let query_str = r#"(string_literal) @str"#;
        let language = tree_sitter_rust::LANGUAGE.into();
        let query = Query::new(&language, query_str).expect("valid query");

        let mut matches_iter = cursor.matches(&query, root, text.as_bytes());
        let mut nodes = Vec::new();
        while let Some(m) = matches_iter.next() {
            nodes.push(m.captures[0].node);
        }

        assert_eq!(nodes.len(), 3, "Should find 3 strings");

        // Create injection regions: lua, python, lua
        let injections = vec![
            InjectionRegionInfo {
                language: "lua".to_string(),
                content_node: nodes[0],
                pattern_index: 0,
                include_children: false,
                offset: None,
                combined: false,
            },
            InjectionRegionInfo {
                language: "python".to_string(),
                content_node: nodes[1],
                pattern_index: 0,
                include_children: false,
                offset: None,
                combined: false,
            },
            InjectionRegionInfo {
                language: "lua".to_string(),
                content_node: nodes[2],
                pattern_index: 0,
                include_children: false,
                offset: None,
                combined: false,
            },
        ];

        // Test finding position inside first Lua block
        let lua1_byte = nodes[0].start_byte() + 1; // Inside first string
        let result = find_injection_at_position(&injections, lua1_byte);
        assert!(result.is_some(), "Should find injection at lua1 position");
        let (idx, region) = result.unwrap();
        assert_eq!(idx, 0, "Should be at index 0");
        assert_eq!(region.language, "lua", "Should be lua region");

        // Test finding position inside Python block
        let py_byte = nodes[1].start_byte() + 1;
        let result = find_injection_at_position(&injections, py_byte);
        assert!(result.is_some(), "Should find injection at python position");
        let (idx, region) = result.unwrap();
        assert_eq!(idx, 1, "Should be at index 1");
        assert_eq!(region.language, "python", "Should be python region");

        // Test finding position inside second Lua block
        let lua2_byte = nodes[2].start_byte() + 1;
        let result = find_injection_at_position(&injections, lua2_byte);
        assert!(result.is_some(), "Should find injection at lua2 position");
        let (idx, region) = result.unwrap();
        assert_eq!(idx, 2, "Should be at index 2");
        assert_eq!(region.language, "lua", "Should be lua region");

        // Test position outside all injections
        let outside_byte = 5; // Position before any string
        let result = find_injection_at_position(&injections, outside_byte);
        assert!(
            result.is_none(),
            "Should not find injection outside regions"
        );
    }

    #[test]
    fn test_collect_all_injections_respects_lua_match_predicate() {
        // Regression test: #lua-match? is a general predicate (not built-in to tree-sitter).
        // collect_all_injections must apply predicate filtering so that injection rules
        // guarded by #lua-match? only match when the predicate actually passes.
        //
        // Without filtering, a rule like:
        //   (string content: _ @injection.content (#lua-match? @injection.content "^;") (#set! injection.language "query"))
        // would match ALL strings, not just those starting with ";".
        let mut parser = create_rust_parser();
        let text = r#"fn main() { let a = "hello"; let b = "; query"; }"#;
        let tree = parse_rust_code(&mut parser, text);
        let root = tree.root_node();

        // Injection query with #lua-match? predicate:
        // Only strings starting with ";" should be injected as "query"
        let query_str = r#"
            ((string_literal
                (string_content) @injection.content)
              (#lua-match? @injection.content "^;")
              (#set! injection.language "query"))
        "#;

        let language = tree_sitter_rust::LANGUAGE.into();
        let query = Query::new(&language, query_str).expect("valid query");

        let injections =
            collect_all_injections(&root, text, Some(&query)).expect("Should return Some");

        // Only "; query" should match, not "hello"
        assert_eq!(
            injections.len(),
            1,
            "Only strings matching #lua-match? should be injected, got: {:?}",
            injections
                .iter()
                .map(|i| &text[i.content_node.start_byte()..i.content_node.end_byte()])
                .collect::<Vec<_>>()
        );
        let content =
            &text[injections[0].content_node.start_byte()..injections[0].content_node.end_byte()];
        assert!(
            content.starts_with(';'),
            "Injected content should start with ';', got: {:?}",
            content
        );
    }

    #[test]
    fn test_collect_all_injections_respects_predicate_on_helper_capture() {
        let mut parser = create_rust_parser();
        let text = "foo!(x)";
        let tree = parse_rust_code(&mut parser, text);
        let root = tree.root_node();

        let query_str = r#"
            ((macro_invocation
                macro: (identifier) @_macro
                (token_tree) @injection.content)
              (#lua-match? @_macro "^html$")
              (#set! injection.language "html"))
        "#;
        let language = tree_sitter_rust::LANGUAGE.into();
        let query = Query::new(&language, query_str).expect("valid query");

        let injections =
            collect_all_injections(&root, text, Some(&query)).expect("injection collection");

        assert!(
            injections.is_empty(),
            "a failed helper-capture predicate must reject the whole match"
        );
    }

    #[test]
    fn test_detect_injection_respects_predicate_on_helper_capture() {
        let mut parser = create_rust_parser();
        let text = "foo!(x)";
        let tree = parse_rust_code(&mut parser, text);
        let root = tree.root_node();
        let node = find_node_at_byte(&root, 5).expect("node inside macro token tree");

        let query_str = r#"
            ((macro_invocation
                macro: (identifier) @_macro
                (token_tree) @injection.content)
              (#lua-match? @_macro "^html$")
              (#set! injection.language "html"))
        "#;
        let language = tree_sitter_rust::LANGUAGE.into();
        let query = Query::new(&language, query_str).expect("valid query");

        let injection = detect_injection(&node, &root, text, Some(&query), "rust");

        assert!(
            injection.is_none(),
            "a failed helper-capture predicate must reject point detection"
        );
    }

    #[rstest]
    #[case::single_line_no_trailing_newline(
        // "hello" sits entirely on row 0; no trailing newline → exclusive end = 1
        r#"let s = "hello";"#,
        0..1,
    )]
    #[case::multi_line_trailing_newline(
        // string_content starts at the byte after `"` on row 0; the content
        // ends with `\n` so end_position().column == 0 at row 4 → exclusive end = 4.
        "let s = \"\nline1\nline2\nline3\n\";",
        0..4,
    )]
    #[case::multi_line_no_trailing_newline(
        // string_content starts on row 0; last line has content (no trailing \n),
        // so end_position().column > 0 at row 2 → exclusive end = 3.
        "let s = \"\nline1\nline2\";",
        0..3,
    )]
    #[trace]
    fn test_line_range_edge_cases(
        #[case] text: &str,
        #[case] expected_line_range: std::ops::Range<u32>,
    ) {
        let cacheable = cacheable_from_first_injection(text);
        assert_eq!(
            cacheable.line_range, expected_line_range,
            "line_range mismatch for text: {:?}",
            text
        );
    }

    #[test]
    fn collects_injected_languages_from_markdown_code_blocks() {
        use std::collections::HashSet;
        use tree_sitter::Query;

        let markdown_text = r#"# Example

```lua
print("Hello from Lua")
local x = 42
```

Some text.

```python
def hello():
    print("Hello from Python")
```

```lua
local y = "duplicate"
```
"#;

        let mut parser = Parser::new();
        let md_language: tree_sitter::Language = tree_sitter_md::LANGUAGE.into();
        parser.set_language(&md_language).expect("set markdown");
        let tree = parser.parse(markdown_text, None).expect("parse markdown");
        let root = tree.root_node();

        let injection_query_str = r#"
            (fenced_code_block
              (info_string
                (language) @injection.language)
              (code_fence_content) @injection.content)
        "#;
        let injection_query =
            Query::new(&md_language, injection_query_str).expect("valid injection query");

        let injections = collect_all_injections(&root, markdown_text, Some(&injection_query))
            .unwrap_or_default();

        let unique_languages: HashSet<String> =
            injections.iter().map(|i| i.language.clone()).collect();

        assert_eq!(unique_languages.len(), 2);
        assert!(unique_languages.contains("lua"));
        assert!(unique_languages.contains("python"));
        assert_eq!(injections.len(), 3, "2 lua + 1 python");
    }

    // --- stale-tree hardening (#401): byte offsets that no longer match `text`
    // must degrade gracefully instead of panicking. ---

    #[test]
    fn position_of_byte_out_of_bounds_does_not_panic() {
        // Offsets past the end, and an anchor landing mid-codepoint (byte 1 of あ).
        let _ = position_of_byte("あ", 99, 50, 0);
        let (row, col) = position_of_byte("あ", 1, 0, 0);
        assert_eq!((row, col), (0, 0));
    }

    #[test]
    fn from_region_info_stale_node_does_not_panic() {
        // A node parsed from `text` but resolved against a much shorter text
        // (as if the document shrank before the tree was refreshed).
        let mut parser = create_rust_parser();
        let text = r#"fn main() { let s = "a fairly long string literal"; }"#;
        let tree = parse_rust_code(&mut parser, text);
        let root = tree.root_node();
        let query_str = r#"((string_literal) @injection.content (#set! injection.language "md"))"#;
        let language = tree_sitter_rust::LANGUAGE.into();
        let query = Query::new(&language, query_str).expect("valid query");
        let regions = collect_all_injections(&root, text, Some(&query)).expect("injections");
        assert!(!regions.is_empty());

        let short_text = "x";
        let cacheable = CacheableInjectionRegion::from_region_info(&regions[0], "id", short_text);
        // Completed without panicking; metadata is still populated.
        assert_eq!(cacheable.language, "md");
        assert_eq!(cacheable.region_id, "id");
        // byte_range is snapped in-bounds, so a downstream `&text[byte_range]`
        // can't panic either.
        assert!(cacheable.byte_range.start <= short_text.len());
        assert!(cacheable.byte_range.end <= short_text.len());
        assert!(cacheable.byte_range.start <= cacheable.byte_range.end);
        assert_eq!(&short_text[cacheable.byte_range.clone()], "");
    }
}
